# Generated by Django 5.1.4 on 2026-03-09 21:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup_idea', models.TextField()),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('target_market', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('solution_summary', models.TextField(blank=True)),
                ('target_market_analysis', models.TextField(blank=True)),
                ('value_proposition', models.TextField(blank=True)),
                ('scalability_analysis', models.TextField(blank=True)),
                ('business_models', models.JSONField(blank=True, default=list)),
                ('competitors', models.JSONField(blank=True, default=list)),
                ('investor_perspective', models.TextField(blank=True)),
                ('investor_verdict', models.CharField(blank=True, max_length=20)),
                ('swot_strengths', models.JSONField(blank=True, default=list)),
                ('swot_weaknesses', models.JSONField(blank=True, default=list)),
                ('swot_opportunities', models.JSONField(blank=True, default=list)),
                ('swot_threats', models.JSONField(blank=True, default=list)),
                ('trend_data', models.JSONField(blank=True, default=dict)),
                ('trend_keywords', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_demand', models.IntegerField(default=0)),
                ('competition_level', models.IntegerField(default=0)),
                ('scalability', models.IntegerField(default=0)),
                ('innovation', models.IntegerField(default=0)),
                ('monetization_potential', models.IntegerField(default=0)),
                ('execution_complexity', models.IntegerField(default=0)),
                ('market_timing', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('score_rationale', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viability_score', to='analysis.startupanalysis')),
            ],
        ),
        migrations.AddIndex(
            model_name='startupanalysis',
            index=models.Index(fields=['user', 'created_at'], name='analysis_st_user_id_e79f37_idx'),
        ),
        migrations.AddIndex(
            model_name='startupanalysis',
            index=models.Index(fields=['status'], name='analysis_st_status_a20cea_idx'),
        ),
    ]
