# Generated by Django 5.1.4 on 2026-03-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_startupanalysis_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupanalysis',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startupanalysis',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
